name: Cross-Platform Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        build_type: [debug, release, dist]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Build ${{ matrix.build_type }}
      run: make ${{ matrix.build_type }}
      
    - name: Test debug build
      if: matrix.build_type == 'debug'
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          .\build-debug\leo-pong.exe
        else
          ./build-debug/leo-pong
        fi
        
    - name: Test release build
      if: matrix.build_type == 'release'
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          .\build-release\leo-pong.exe
        else
          ./build-release/leo-pong
        fi
        
    - name: Test dist build
      if: matrix.build_type == 'dist'
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          .\build-release-dist\bin\Release\leo-pong.exe
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          ./build-release-dist/leo-pong.app/Contents/MacOS/leo-pong
        else
          ./build-release-dist/leo-pong
        fi
        
    - name: Upload debug artifact
      if: matrix.build_type == 'debug'
      uses: actions/upload-artifact@v4
      with:
        name: leo-pong-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}-debug
        path: |
          build-debug/leo-pong${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          
    - name: Upload release artifact
      if: matrix.build_type == 'release'
      uses: actions/upload-artifact@v4
      with:
        name: leo-pong-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}-release
        path: |
          build-release/leo-pong${{ matrix.os == 'windows-latest' && '.exe' || '' }}
          
    - name: Upload distribution artifact
      if: matrix.build_type == 'dist'
      uses: actions/upload-artifact@v4
      with:
        name: leo-pong-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}
        path: dist/
