name: Cross-Platform Build

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake
        
    - name: Configure CMake
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release
      
    - name: Build
      run: cmake --build build --config Release
      
    - name: Test run (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        .\build\bin\Release\leo-pong.exe
        
    - name: Test run (Unix)
      if: matrix.os != 'windows-latest'
      run: |
        if [ "${{ matrix.os }}" = "macos-latest" ]; then
          ./build/leo-pong.app/Contents/MacOS/leo-pong
        else
          ./build/leo-pong
        fi
        
    - name: Create distribution
      run: make install
      
    - name: Upload distribution artifact
      uses: actions/upload-artifact@v4
      with:
        name: leo-pong-${{ matrix.os == 'ubuntu-latest' && 'linux' || matrix.os == 'windows-latest' && 'windows' || 'macos' }}
        path: dist/
